// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package instagram

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF42599adDecodeGithubComStounhandJShortsForwardInternalDownloadersInstagram(in *jlexer.Lexer, out *videoObject) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]videoData, 0, 0)
					} else {
						out.Items = []videoData{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v1 videoData
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Items = append(out.Items, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF42599adEncodeGithubComStounhandJShortsForwardInternalDownloadersInstagram(out *jwriter.Writer, in videoObject) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"items\":"
		out.RawString(prefix[1:])
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Items {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v videoObject) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF42599adEncodeGithubComStounhandJShortsForwardInternalDownloadersInstagram(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v videoObject) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF42599adEncodeGithubComStounhandJShortsForwardInternalDownloadersInstagram(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *videoObject) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF42599adDecodeGithubComStounhandJShortsForwardInternalDownloadersInstagram(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *videoObject) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF42599adDecodeGithubComStounhandJShortsForwardInternalDownloadersInstagram(l, v)
}
func easyjsonF42599adDecodeGithubComStounhandJShortsForwardInternalDownloadersInstagram1(in *jlexer.Lexer, out *videoData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "video_versions":
			if in.IsNull() {
				in.Skip()
				out.VideoVersions = nil
			} else {
				in.Delim('[')
				if out.VideoVersions == nil {
					if !in.IsDelim(']') {
						out.VideoVersions = make([]struct {
							URL  string `json:"url"`
							Type int    `json:"type"`
						}, 0, 2)
					} else {
						out.VideoVersions = []struct {
							URL  string `json:"url"`
							Type int    `json:"type"`
						}{}
					}
				} else {
					out.VideoVersions = (out.VideoVersions)[:0]
				}
				for !in.IsDelim(']') {
					var v4 struct {
						URL  string `json:"url"`
						Type int    `json:"type"`
					}
					easyjsonF42599adDecode(in, &v4)
					out.VideoVersions = append(out.VideoVersions, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "image_versions2":
			easyjsonF42599adDecode1(in, &out.ImageVersions)
		case "caption":
			easyjsonF42599adDecode2(in, &out.Caption)
		case "like_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LikeCount = int(in.Int())
			}
		case "video_dash_manifest":
			if in.IsNull() {
				in.Skip()
			} else {
				out.VideoDashManifest = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF42599adEncodeGithubComStounhandJShortsForwardInternalDownloadersInstagram1(out *jwriter.Writer, in videoData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"video_versions\":"
		out.RawString(prefix)
		if in.VideoVersions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.VideoVersions {
				if v5 > 0 {
					out.RawByte(',')
				}
				easyjsonF42599adEncode(out, v6)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"image_versions2\":"
		out.RawString(prefix)
		easyjsonF42599adEncode1(out, in.ImageVersions)
	}
	{
		const prefix string = ",\"caption\":"
		out.RawString(prefix)
		easyjsonF42599adEncode2(out, in.Caption)
	}
	{
		const prefix string = ",\"like_count\":"
		out.RawString(prefix)
		out.Int(int(in.LikeCount))
	}
	{
		const prefix string = ",\"video_dash_manifest\":"
		out.RawString(prefix)
		out.String(string(in.VideoDashManifest))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v videoData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF42599adEncodeGithubComStounhandJShortsForwardInternalDownloadersInstagram1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v videoData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF42599adEncodeGithubComStounhandJShortsForwardInternalDownloadersInstagram1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *videoData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF42599adDecodeGithubComStounhandJShortsForwardInternalDownloadersInstagram1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *videoData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF42599adDecodeGithubComStounhandJShortsForwardInternalDownloadersInstagram1(l, v)
}
func easyjsonF42599adDecode2(in *jlexer.Lexer, out *struct {
	Text string `json:"text"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "text":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Text = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF42599adEncode2(out *jwriter.Writer, in struct {
	Text string `json:"text"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix[1:])
		out.String(string(in.Text))
	}
	out.RawByte('}')
}
func easyjsonF42599adDecode1(in *jlexer.Lexer, out *struct {
	Candidates []struct {
		URL string `json:"url"`
	} `json:"candidates"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "candidates":
			if in.IsNull() {
				in.Skip()
				out.Candidates = nil
			} else {
				in.Delim('[')
				if out.Candidates == nil {
					if !in.IsDelim(']') {
						out.Candidates = make([]struct {
							URL string `json:"url"`
						}, 0, 4)
					} else {
						out.Candidates = []struct {
							URL string `json:"url"`
						}{}
					}
				} else {
					out.Candidates = (out.Candidates)[:0]
				}
				for !in.IsDelim(']') {
					var v7 struct {
						URL string `json:"url"`
					}
					easyjsonF42599adDecode3(in, &v7)
					out.Candidates = append(out.Candidates, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF42599adEncode1(out *jwriter.Writer, in struct {
	Candidates []struct {
		URL string `json:"url"`
	} `json:"candidates"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"candidates\":"
		out.RawString(prefix[1:])
		if in.Candidates == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Candidates {
				if v8 > 0 {
					out.RawByte(',')
				}
				easyjsonF42599adEncode3(out, v9)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjsonF42599adDecode3(in *jlexer.Lexer, out *struct {
	URL string `json:"url"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF42599adEncode3(out *jwriter.Writer, in struct {
	URL string `json:"url"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	out.RawByte('}')
}
func easyjsonF42599adDecode(in *jlexer.Lexer, out *struct {
	URL  string `json:"url"`
	Type int    `json:"type"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "url":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URL = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF42599adEncode(out *jwriter.Writer, in struct {
	URL  string `json:"url"`
	Type int    `json:"type"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix[1:])
		out.String(string(in.URL))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.Int(int(in.Type))
	}
	out.RawByte('}')
}
