version: "2"

run:
  timeout: 5m
  tests: false

linters:
  enable:
    #####################################################
    # 🔧 Базовые и обязательные линтеры (общие ошибки)
    #####################################################
    - errcheck          # Проверка необработанных ошибок
    - govet             # Встроенный в Go анализатор подозрительных конструкций
    - staticcheck       # Набор статических проверок (более строгий, чем vet)

    #####################################################
    # 🧹 Простота и чистота кода
    #####################################################
    - ineffassign       # Неиспользуемые присваивания
    - unused            # Неиспользуемые переменные, функции, типы и т. д.
    - goconst           # Повторяющиеся строки и числа → константы
    - gocritic          # Разнообразные проверки на стиль и баги
    # - revive            # Современный аналог golint (документация, стиль)

    #####################################################
    # 💡 Стиль, читаемость и авто-правки
    #####################################################
    - misspell          # Орфографические ошибки в комментариях и коде
    - nlreturn          # Отступ перед return / if для читаемости
    - wsl_v5            # Отступы и пустые строки

    #####################################################
    # 🧠 Архитектура и структура
    #####################################################
    # - funlen            # Слишком длинные функции
    - cyclop            # Цикломатическая сложность
    - gocyclo           # Аналогично cyclop
    # - nestif            # Глубоко вложенные if
    - unparam           # Неиспользуемые параметры
    - interfacebloat    # Слишком "толстые" интерфейсы

    #####################################################
    # 🛡️ Безопасность и корректность
    #####################################################
    - errorlint         # Проверка корректного оборачивания ошибок (%w, errors.Is/As)
    # - wrapcheck         # Убедиться, что возвращаемые ошибки обёрнуты
    # - gosec             # Статический анализ на безопасность
    - bodyclose         # Закрытие HTTP response body
    - rowserrcheck      # Проверка rows.Err после перебора sql.Rows
    - sqlclosecheck     # Проверка закрытия SQL-ресурсов
    - noctx             # Сетевые вызовы должны использовать context
  
  settings:
    wsl_v5:
      allow-first-in-block: false
      allow-whole-block: true
      disable:
        - decl
        
    interfacebloat:
      max: 15                           # Увеличить лимит методов в интерфейсе

    cyclop:
      max-complexity: 50                # Увеличить лимит сложности метода и циклов

    errcheck:
      check-type-assertions: true
      check-blank: true

    unused:
      exported-fields-are-used: false   # Экспортированные поля структур (с большой буквы) не отмечаются как используемые (при false)
      parameters-are-used: true         # Параметры функций, даже если они не используются внутри, будут восприниматься как неиспользуемые (при false)
      field-writes-are-uses: false      # Поля структур, в которые только записывается значение, не считаются использованными (при false)
      post-statements-are-reads: true   # Инкременты/декременты (i++, i--) трактуются как чтение (при true)
      local-variables-are-used: false   # Локальные переменные, которые объявлены, но не используются - также будут отмечены как неиспользуемые (при false)

  exclusions:
    paths:
      - vendor
      - docs
      - migrations
      - testdata
      - scripts
      - ".*_generated.go"
      - ".*.pb.go"


formatters:
  enable:
    - goimports         # Форматирование и порядок импортов
    - gofumpt           # Строгая версия gofmt (с дополнительными правилами)

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true

output:
  formats:
    text:
      path: stdout
      colors: true
      print-linter-name: false
