// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package tiktok

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonC1cedd36DecodeGithubComStounhandJShortsForwardInternalDownloadersTikTok(in *jlexer.Lexer, out *ApiResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = int(in.Int())
			}
		case "msg":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Msg = string(in.String())
			}
		case "processed_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ProcessedTime = float64(in.Float64())
			}
		case "data":
			easyjsonC1cedd36Decode(in, &out.Data)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1cedd36EncodeGithubComStounhandJShortsForwardInternalDownloadersTikTok(out *jwriter.Writer, in ApiResponse) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Code != 0 {
		const prefix string = ",\"code\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.Code))
	}
	{
		const prefix string = ",\"msg\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Msg))
	}
	if in.ProcessedTime != 0 {
		const prefix string = ",\"processed_time\":"
		out.RawString(prefix)
		out.Float64(float64(in.ProcessedTime))
	}
	if true {
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		easyjsonC1cedd36Encode(out, in.Data)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ApiResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonC1cedd36EncodeGithubComStounhandJShortsForwardInternalDownloadersTikTok(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ApiResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonC1cedd36EncodeGithubComStounhandJShortsForwardInternalDownloadersTikTok(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ApiResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonC1cedd36DecodeGithubComStounhandJShortsForwardInternalDownloadersTikTok(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ApiResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonC1cedd36DecodeGithubComStounhandJShortsForwardInternalDownloadersTikTok(l, v)
}
func easyjsonC1cedd36Decode(in *jlexer.Lexer, out *struct {
	ID             string `json:"id,omitempty"`
	Region         string `json:"region,omitempty"`
	Title          string `json:"title,omitempty"`
	Cover          string `json:"cover,omitempty"`
	AiDynamicCover string `json:"ai_dynamic_cover,omitempty"`
	OriginCover    string `json:"origin_cover,omitempty"`
	Duration       int    `json:"duration,omitempty"`
	Play           string `json:"play,omitempty"`
	Hdplay         string `json:"hdplay,omitempty"`
	Wmplay         string `json:"wmplay,omitempty"`
	Size           int    `json:"size,omitempty"`
	WmSize         int    `json:"wm_size,omitempty"`
	HdSize         int    `json:"hd_size,omitempty"`
	Music          string `json:"music,omitempty"`
	MusicInfo      struct {
		ID       string `json:"id,omitempty"`
		Title    string `json:"title,omitempty"`
		Play     string `json:"play,omitempty"`
		Cover    string `json:"cover,omitempty"`
		Author   string `json:"author,omitempty"`
		Original bool   `json:"original,omitempty"`
		Duration int    `json:"duration,omitempty"`
		Album    string `json:"album,omitempty"`
	} `json:"music_info,omitempty"`
	PlayCount     int `json:"play_count,omitempty"`
	DiggCount     int `json:"digg_count,omitempty"`
	CommentCount  int `json:"comment_count,omitempty"`
	ShareCount    int `json:"share_count,omitempty"`
	DownloadCount int `json:"download_count,omitempty"`
	CollectCount  int `json:"collect_count,omitempty"`
	CreateTime    int `json:"create_time,omitempty"`
	Anchors       []struct {
		Actions      []interface{} `json:"actions,omitempty"`
		AnchorStrong interface{}   `json:"anchor_strong,omitempty"`
		ComponentKey string        `json:"component_key,omitempty"`
		Description  string        `json:"description,omitempty"`
		Extra        string        `json:"extra,omitempty"`
		GeneralType  int           `json:"general_type,omitempty"`
		Icon         struct {
			Height    int         `json:"height,omitempty"`
			URI       string      `json:"uri,omitempty"`
			URLList   []string    `json:"url_list,omitempty"`
			URLPrefix interface{} `json:"url_prefix,omitempty"`
			Width     int         `json:"width,omitempty"`
		} `json:"icon,omitempty"`
		ID        string `json:"id,omitempty"`
		Keyword   string `json:"keyword,omitempty"`
		LogExtra  string `json:"log_extra,omitempty"`
		Schema    string `json:"schema,omitempty"`
		Thumbnail struct {
			Height    int         `json:"height,omitempty"`
			URI       string      `json:"uri,omitempty"`
			URLList   []string    `json:"url_list,omitempty"`
			URLPrefix interface{} `json:"url_prefix,omitempty"`
			Width     int         `json:"width,omitempty"`
		} `json:"thumbnail,omitempty"`
		Type int `json:"type,omitempty"`
	} `json:"anchors,omitempty"`
	AnchorsExtras string `json:"anchors_extras,omitempty"`
	IsAd          bool   `json:"is_ad,omitempty"`
	CommerceInfo  struct {
		AdvPromotable          bool `json:"adv_promotable,omitempty"`
		AuctionAdInvited       bool `json:"auction_ad_invited,omitempty"`
		BrandedContentType     int  `json:"branded_content_type,omitempty"`
		WithCommentFilterWords bool `json:"with_comment_filter_words,omitempty"`
	} `json:"commerce_info,omitempty"`
	CommercialVideoInfo string `json:"commercial_video_info,omitempty"`
	ItemCommentSettings int    `json:"item_comment_settings,omitempty"`
	MentionedUsers      string `json:"mentioned_users,omitempty"`
	Author              struct {
		ID       string `json:"id,omitempty"`
		UniqueID string `json:"unique_id,omitempty"`
		Nickname string `json:"nickname,omitempty"`
		Avatar   string `json:"avatar,omitempty"`
	} `json:"author,omitempty"`
	Images []string `json:"images,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "region":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Region = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "cover":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cover = string(in.String())
			}
		case "ai_dynamic_cover":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AiDynamicCover = string(in.String())
			}
		case "origin_cover":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OriginCover = string(in.String())
			}
		case "duration":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Duration = int(in.Int())
			}
		case "play":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Play = string(in.String())
			}
		case "hdplay":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Hdplay = string(in.String())
			}
		case "wmplay":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Wmplay = string(in.String())
			}
		case "size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Size = int(in.Int())
			}
		case "wm_size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WmSize = int(in.Int())
			}
		case "hd_size":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HdSize = int(in.Int())
			}
		case "music":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Music = string(in.String())
			}
		case "music_info":
			easyjsonC1cedd36Decode1(in, &out.MusicInfo)
		case "play_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PlayCount = int(in.Int())
			}
		case "digg_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DiggCount = int(in.Int())
			}
		case "comment_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CommentCount = int(in.Int())
			}
		case "share_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ShareCount = int(in.Int())
			}
		case "download_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DownloadCount = int(in.Int())
			}
		case "collect_count":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CollectCount = int(in.Int())
			}
		case "create_time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreateTime = int(in.Int())
			}
		case "anchors":
			if in.IsNull() {
				in.Skip()
				out.Anchors = nil
			} else {
				in.Delim('[')
				if out.Anchors == nil {
					if !in.IsDelim(']') {
						out.Anchors = make([]struct {
							Actions      []interface{} `json:"actions,omitempty"`
							AnchorStrong interface{}   `json:"anchor_strong,omitempty"`
							ComponentKey string        `json:"component_key,omitempty"`
							Description  string        `json:"description,omitempty"`
							Extra        string        `json:"extra,omitempty"`
							GeneralType  int           `json:"general_type,omitempty"`
							Icon         struct {
								Height    int         `json:"height,omitempty"`
								URI       string      `json:"uri,omitempty"`
								URLList   []string    `json:"url_list,omitempty"`
								URLPrefix interface{} `json:"url_prefix,omitempty"`
								Width     int         `json:"width,omitempty"`
							} `json:"icon,omitempty"`
							ID        string `json:"id,omitempty"`
							Keyword   string `json:"keyword,omitempty"`
							LogExtra  string `json:"log_extra,omitempty"`
							Schema    string `json:"schema,omitempty"`
							Thumbnail struct {
								Height    int         `json:"height,omitempty"`
								URI       string      `json:"uri,omitempty"`
								URLList   []string    `json:"url_list,omitempty"`
								URLPrefix interface{} `json:"url_prefix,omitempty"`
								Width     int         `json:"width,omitempty"`
							} `json:"thumbnail,omitempty"`
							Type int `json:"type,omitempty"`
						}, 0, 0)
					} else {
						out.Anchors = []struct {
							Actions      []interface{} `json:"actions,omitempty"`
							AnchorStrong interface{}   `json:"anchor_strong,omitempty"`
							ComponentKey string        `json:"component_key,omitempty"`
							Description  string        `json:"description,omitempty"`
							Extra        string        `json:"extra,omitempty"`
							GeneralType  int           `json:"general_type,omitempty"`
							Icon         struct {
								Height    int         `json:"height,omitempty"`
								URI       string      `json:"uri,omitempty"`
								URLList   []string    `json:"url_list,omitempty"`
								URLPrefix interface{} `json:"url_prefix,omitempty"`
								Width     int         `json:"width,omitempty"`
							} `json:"icon,omitempty"`
							ID        string `json:"id,omitempty"`
							Keyword   string `json:"keyword,omitempty"`
							LogExtra  string `json:"log_extra,omitempty"`
							Schema    string `json:"schema,omitempty"`
							Thumbnail struct {
								Height    int         `json:"height,omitempty"`
								URI       string      `json:"uri,omitempty"`
								URLList   []string    `json:"url_list,omitempty"`
								URLPrefix interface{} `json:"url_prefix,omitempty"`
								Width     int         `json:"width,omitempty"`
							} `json:"thumbnail,omitempty"`
							Type int `json:"type,omitempty"`
						}{}
					}
				} else {
					out.Anchors = (out.Anchors)[:0]
				}
				for !in.IsDelim(']') {
					var v1 struct {
						Actions      []interface{} `json:"actions,omitempty"`
						AnchorStrong interface{}   `json:"anchor_strong,omitempty"`
						ComponentKey string        `json:"component_key,omitempty"`
						Description  string        `json:"description,omitempty"`
						Extra        string        `json:"extra,omitempty"`
						GeneralType  int           `json:"general_type,omitempty"`
						Icon         struct {
							Height    int         `json:"height,omitempty"`
							URI       string      `json:"uri,omitempty"`
							URLList   []string    `json:"url_list,omitempty"`
							URLPrefix interface{} `json:"url_prefix,omitempty"`
							Width     int         `json:"width,omitempty"`
						} `json:"icon,omitempty"`
						ID        string `json:"id,omitempty"`
						Keyword   string `json:"keyword,omitempty"`
						LogExtra  string `json:"log_extra,omitempty"`
						Schema    string `json:"schema,omitempty"`
						Thumbnail struct {
							Height    int         `json:"height,omitempty"`
							URI       string      `json:"uri,omitempty"`
							URLList   []string    `json:"url_list,omitempty"`
							URLPrefix interface{} `json:"url_prefix,omitempty"`
							Width     int         `json:"width,omitempty"`
						} `json:"thumbnail,omitempty"`
						Type int `json:"type,omitempty"`
					}
					easyjsonC1cedd36Decode2(in, &v1)
					out.Anchors = append(out.Anchors, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "anchors_extras":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AnchorsExtras = string(in.String())
			}
		case "is_ad":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsAd = bool(in.Bool())
			}
		case "commerce_info":
			easyjsonC1cedd36Decode3(in, &out.CommerceInfo)
		case "commercial_video_info":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CommercialVideoInfo = string(in.String())
			}
		case "item_comment_settings":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ItemCommentSettings = int(in.Int())
			}
		case "mentioned_users":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MentionedUsers = string(in.String())
			}
		case "author":
			easyjsonC1cedd36Decode4(in, &out.Author)
		case "images":
			if in.IsNull() {
				in.Skip()
				out.Images = nil
			} else {
				in.Delim('[')
				if out.Images == nil {
					if !in.IsDelim(']') {
						out.Images = make([]string, 0, 4)
					} else {
						out.Images = []string{}
					}
				} else {
					out.Images = (out.Images)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					out.Images = append(out.Images, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1cedd36Encode(out *jwriter.Writer, in struct {
	ID             string `json:"id,omitempty"`
	Region         string `json:"region,omitempty"`
	Title          string `json:"title,omitempty"`
	Cover          string `json:"cover,omitempty"`
	AiDynamicCover string `json:"ai_dynamic_cover,omitempty"`
	OriginCover    string `json:"origin_cover,omitempty"`
	Duration       int    `json:"duration,omitempty"`
	Play           string `json:"play,omitempty"`
	Hdplay         string `json:"hdplay,omitempty"`
	Wmplay         string `json:"wmplay,omitempty"`
	Size           int    `json:"size,omitempty"`
	WmSize         int    `json:"wm_size,omitempty"`
	HdSize         int    `json:"hd_size,omitempty"`
	Music          string `json:"music,omitempty"`
	MusicInfo      struct {
		ID       string `json:"id,omitempty"`
		Title    string `json:"title,omitempty"`
		Play     string `json:"play,omitempty"`
		Cover    string `json:"cover,omitempty"`
		Author   string `json:"author,omitempty"`
		Original bool   `json:"original,omitempty"`
		Duration int    `json:"duration,omitempty"`
		Album    string `json:"album,omitempty"`
	} `json:"music_info,omitempty"`
	PlayCount     int `json:"play_count,omitempty"`
	DiggCount     int `json:"digg_count,omitempty"`
	CommentCount  int `json:"comment_count,omitempty"`
	ShareCount    int `json:"share_count,omitempty"`
	DownloadCount int `json:"download_count,omitempty"`
	CollectCount  int `json:"collect_count,omitempty"`
	CreateTime    int `json:"create_time,omitempty"`
	Anchors       []struct {
		Actions      []interface{} `json:"actions,omitempty"`
		AnchorStrong interface{}   `json:"anchor_strong,omitempty"`
		ComponentKey string        `json:"component_key,omitempty"`
		Description  string        `json:"description,omitempty"`
		Extra        string        `json:"extra,omitempty"`
		GeneralType  int           `json:"general_type,omitempty"`
		Icon         struct {
			Height    int         `json:"height,omitempty"`
			URI       string      `json:"uri,omitempty"`
			URLList   []string    `json:"url_list,omitempty"`
			URLPrefix interface{} `json:"url_prefix,omitempty"`
			Width     int         `json:"width,omitempty"`
		} `json:"icon,omitempty"`
		ID        string `json:"id,omitempty"`
		Keyword   string `json:"keyword,omitempty"`
		LogExtra  string `json:"log_extra,omitempty"`
		Schema    string `json:"schema,omitempty"`
		Thumbnail struct {
			Height    int         `json:"height,omitempty"`
			URI       string      `json:"uri,omitempty"`
			URLList   []string    `json:"url_list,omitempty"`
			URLPrefix interface{} `json:"url_prefix,omitempty"`
			Width     int         `json:"width,omitempty"`
		} `json:"thumbnail,omitempty"`
		Type int `json:"type,omitempty"`
	} `json:"anchors,omitempty"`
	AnchorsExtras string `json:"anchors_extras,omitempty"`
	IsAd          bool   `json:"is_ad,omitempty"`
	CommerceInfo  struct {
		AdvPromotable          bool `json:"adv_promotable,omitempty"`
		AuctionAdInvited       bool `json:"auction_ad_invited,omitempty"`
		BrandedContentType     int  `json:"branded_content_type,omitempty"`
		WithCommentFilterWords bool `json:"with_comment_filter_words,omitempty"`
	} `json:"commerce_info,omitempty"`
	CommercialVideoInfo string `json:"commercial_video_info,omitempty"`
	ItemCommentSettings int    `json:"item_comment_settings,omitempty"`
	MentionedUsers      string `json:"mentioned_users,omitempty"`
	Author              struct {
		ID       string `json:"id,omitempty"`
		UniqueID string `json:"unique_id,omitempty"`
		Nickname string `json:"nickname,omitempty"`
		Avatar   string `json:"avatar,omitempty"`
	} `json:"author,omitempty"`
	Images []string `json:"images,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != "" {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	if in.Region != "" {
		const prefix string = ",\"region\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Region))
	}
	if in.Title != "" {
		const prefix string = ",\"title\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Title))
	}
	if in.Cover != "" {
		const prefix string = ",\"cover\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Cover))
	}
	if in.AiDynamicCover != "" {
		const prefix string = ",\"ai_dynamic_cover\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AiDynamicCover))
	}
	if in.OriginCover != "" {
		const prefix string = ",\"origin_cover\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.OriginCover))
	}
	if in.Duration != 0 {
		const prefix string = ",\"duration\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Duration))
	}
	if in.Play != "" {
		const prefix string = ",\"play\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Play))
	}
	if in.Hdplay != "" {
		const prefix string = ",\"hdplay\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Hdplay))
	}
	if in.Wmplay != "" {
		const prefix string = ",\"wmplay\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Wmplay))
	}
	if in.Size != 0 {
		const prefix string = ",\"size\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Size))
	}
	if in.WmSize != 0 {
		const prefix string = ",\"wm_size\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.WmSize))
	}
	if in.HdSize != 0 {
		const prefix string = ",\"hd_size\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.HdSize))
	}
	if in.Music != "" {
		const prefix string = ",\"music\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Music))
	}
	if true {
		const prefix string = ",\"music_info\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjsonC1cedd36Encode1(out, in.MusicInfo)
	}
	if in.PlayCount != 0 {
		const prefix string = ",\"play_count\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.PlayCount))
	}
	if in.DiggCount != 0 {
		const prefix string = ",\"digg_count\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.DiggCount))
	}
	if in.CommentCount != 0 {
		const prefix string = ",\"comment_count\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.CommentCount))
	}
	if in.ShareCount != 0 {
		const prefix string = ",\"share_count\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ShareCount))
	}
	if in.DownloadCount != 0 {
		const prefix string = ",\"download_count\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.DownloadCount))
	}
	if in.CollectCount != 0 {
		const prefix string = ",\"collect_count\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.CollectCount))
	}
	if in.CreateTime != 0 {
		const prefix string = ",\"create_time\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.CreateTime))
	}
	if len(in.Anchors) != 0 {
		const prefix string = ",\"anchors\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v3, v4 := range in.Anchors {
				if v3 > 0 {
					out.RawByte(',')
				}
				easyjsonC1cedd36Encode2(out, v4)
			}
			out.RawByte(']')
		}
	}
	if in.AnchorsExtras != "" {
		const prefix string = ",\"anchors_extras\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AnchorsExtras))
	}
	if in.IsAd {
		const prefix string = ",\"is_ad\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.IsAd))
	}
	if true {
		const prefix string = ",\"commerce_info\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjsonC1cedd36Encode3(out, in.CommerceInfo)
	}
	if in.CommercialVideoInfo != "" {
		const prefix string = ",\"commercial_video_info\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.CommercialVideoInfo))
	}
	if in.ItemCommentSettings != 0 {
		const prefix string = ",\"item_comment_settings\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.ItemCommentSettings))
	}
	if in.MentionedUsers != "" {
		const prefix string = ",\"mentioned_users\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.MentionedUsers))
	}
	if true {
		const prefix string = ",\"author\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjsonC1cedd36Encode4(out, in.Author)
	}
	if len(in.Images) != 0 {
		const prefix string = ",\"images\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v5, v6 := range in.Images {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}
func easyjsonC1cedd36Decode4(in *jlexer.Lexer, out *struct {
	ID       string `json:"id,omitempty"`
	UniqueID string `json:"unique_id,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	Avatar   string `json:"avatar,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "unique_id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UniqueID = string(in.String())
			}
		case "nickname":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Nickname = string(in.String())
			}
		case "avatar":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Avatar = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1cedd36Encode4(out *jwriter.Writer, in struct {
	ID       string `json:"id,omitempty"`
	UniqueID string `json:"unique_id,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	Avatar   string `json:"avatar,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != "" {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	if in.UniqueID != "" {
		const prefix string = ",\"unique_id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.UniqueID))
	}
	if in.Nickname != "" {
		const prefix string = ",\"nickname\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Nickname))
	}
	if in.Avatar != "" {
		const prefix string = ",\"avatar\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Avatar))
	}
	out.RawByte('}')
}
func easyjsonC1cedd36Decode3(in *jlexer.Lexer, out *struct {
	AdvPromotable          bool `json:"adv_promotable,omitempty"`
	AuctionAdInvited       bool `json:"auction_ad_invited,omitempty"`
	BrandedContentType     int  `json:"branded_content_type,omitempty"`
	WithCommentFilterWords bool `json:"with_comment_filter_words,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "adv_promotable":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AdvPromotable = bool(in.Bool())
			}
		case "auction_ad_invited":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AuctionAdInvited = bool(in.Bool())
			}
		case "branded_content_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BrandedContentType = int(in.Int())
			}
		case "with_comment_filter_words":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WithCommentFilterWords = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1cedd36Encode3(out *jwriter.Writer, in struct {
	AdvPromotable          bool `json:"adv_promotable,omitempty"`
	AuctionAdInvited       bool `json:"auction_ad_invited,omitempty"`
	BrandedContentType     int  `json:"branded_content_type,omitempty"`
	WithCommentFilterWords bool `json:"with_comment_filter_words,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.AdvPromotable {
		const prefix string = ",\"adv_promotable\":"
		first = false
		out.RawString(prefix[1:])
		out.Bool(bool(in.AdvPromotable))
	}
	if in.AuctionAdInvited {
		const prefix string = ",\"auction_ad_invited\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.AuctionAdInvited))
	}
	if in.BrandedContentType != 0 {
		const prefix string = ",\"branded_content_type\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.BrandedContentType))
	}
	if in.WithCommentFilterWords {
		const prefix string = ",\"with_comment_filter_words\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.WithCommentFilterWords))
	}
	out.RawByte('}')
}
func easyjsonC1cedd36Decode2(in *jlexer.Lexer, out *struct {
	Actions      []interface{} `json:"actions,omitempty"`
	AnchorStrong interface{}   `json:"anchor_strong,omitempty"`
	ComponentKey string        `json:"component_key,omitempty"`
	Description  string        `json:"description,omitempty"`
	Extra        string        `json:"extra,omitempty"`
	GeneralType  int           `json:"general_type,omitempty"`
	Icon         struct {
		Height    int         `json:"height,omitempty"`
		URI       string      `json:"uri,omitempty"`
		URLList   []string    `json:"url_list,omitempty"`
		URLPrefix interface{} `json:"url_prefix,omitempty"`
		Width     int         `json:"width,omitempty"`
	} `json:"icon,omitempty"`
	ID        string `json:"id,omitempty"`
	Keyword   string `json:"keyword,omitempty"`
	LogExtra  string `json:"log_extra,omitempty"`
	Schema    string `json:"schema,omitempty"`
	Thumbnail struct {
		Height    int         `json:"height,omitempty"`
		URI       string      `json:"uri,omitempty"`
		URLList   []string    `json:"url_list,omitempty"`
		URLPrefix interface{} `json:"url_prefix,omitempty"`
		Width     int         `json:"width,omitempty"`
	} `json:"thumbnail,omitempty"`
	Type int `json:"type,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "actions":
			if in.IsNull() {
				in.Skip()
				out.Actions = nil
			} else {
				in.Delim('[')
				if out.Actions == nil {
					if !in.IsDelim(']') {
						out.Actions = make([]interface{}, 0, 4)
					} else {
						out.Actions = []interface{}{}
					}
				} else {
					out.Actions = (out.Actions)[:0]
				}
				for !in.IsDelim(']') {
					var v7 interface{}
					if m, ok := v7.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v7.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v7 = in.Interface()
					}
					out.Actions = append(out.Actions, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "anchor_strong":
			if m, ok := out.AnchorStrong.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.AnchorStrong.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.AnchorStrong = in.Interface()
			}
		case "component_key":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ComponentKey = string(in.String())
			}
		case "description":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Description = string(in.String())
			}
		case "extra":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Extra = string(in.String())
			}
		case "general_type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.GeneralType = int(in.Int())
			}
		case "icon":
			easyjsonC1cedd36Decode5(in, &out.Icon)
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "keyword":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Keyword = string(in.String())
			}
		case "log_extra":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LogExtra = string(in.String())
			}
		case "schema":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Schema = string(in.String())
			}
		case "thumbnail":
			easyjsonC1cedd36Decode5(in, &out.Thumbnail)
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1cedd36Encode2(out *jwriter.Writer, in struct {
	Actions      []interface{} `json:"actions,omitempty"`
	AnchorStrong interface{}   `json:"anchor_strong,omitempty"`
	ComponentKey string        `json:"component_key,omitempty"`
	Description  string        `json:"description,omitempty"`
	Extra        string        `json:"extra,omitempty"`
	GeneralType  int           `json:"general_type,omitempty"`
	Icon         struct {
		Height    int         `json:"height,omitempty"`
		URI       string      `json:"uri,omitempty"`
		URLList   []string    `json:"url_list,omitempty"`
		URLPrefix interface{} `json:"url_prefix,omitempty"`
		Width     int         `json:"width,omitempty"`
	} `json:"icon,omitempty"`
	ID        string `json:"id,omitempty"`
	Keyword   string `json:"keyword,omitempty"`
	LogExtra  string `json:"log_extra,omitempty"`
	Schema    string `json:"schema,omitempty"`
	Thumbnail struct {
		Height    int         `json:"height,omitempty"`
		URI       string      `json:"uri,omitempty"`
		URLList   []string    `json:"url_list,omitempty"`
		URLPrefix interface{} `json:"url_prefix,omitempty"`
		Width     int         `json:"width,omitempty"`
	} `json:"thumbnail,omitempty"`
	Type int `json:"type,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if len(in.Actions) != 0 {
		const prefix string = ",\"actions\":"
		first = false
		out.RawString(prefix[1:])
		{
			out.RawByte('[')
			for v8, v9 := range in.Actions {
				if v8 > 0 {
					out.RawByte(',')
				}
				if m, ok := v9.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v9.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v9))
				}
			}
			out.RawByte(']')
		}
	}
	if in.AnchorStrong != nil {
		const prefix string = ",\"anchor_strong\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if m, ok := in.AnchorStrong.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.AnchorStrong.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.AnchorStrong))
		}
	}
	if in.ComponentKey != "" {
		const prefix string = ",\"component_key\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ComponentKey))
	}
	if in.Description != "" {
		const prefix string = ",\"description\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Description))
	}
	if in.Extra != "" {
		const prefix string = ",\"extra\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Extra))
	}
	if in.GeneralType != 0 {
		const prefix string = ",\"general_type\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.GeneralType))
	}
	if true {
		const prefix string = ",\"icon\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjsonC1cedd36Encode5(out, in.Icon)
	}
	if in.ID != "" {
		const prefix string = ",\"id\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.ID))
	}
	if in.Keyword != "" {
		const prefix string = ",\"keyword\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Keyword))
	}
	if in.LogExtra != "" {
		const prefix string = ",\"log_extra\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.LogExtra))
	}
	if in.Schema != "" {
		const prefix string = ",\"schema\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Schema))
	}
	if true {
		const prefix string = ",\"thumbnail\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		easyjsonC1cedd36Encode5(out, in.Thumbnail)
	}
	if in.Type != 0 {
		const prefix string = ",\"type\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Type))
	}
	out.RawByte('}')
}
func easyjsonC1cedd36Decode5(in *jlexer.Lexer, out *struct {
	Height    int         `json:"height,omitempty"`
	URI       string      `json:"uri,omitempty"`
	URLList   []string    `json:"url_list,omitempty"`
	URLPrefix interface{} `json:"url_prefix,omitempty"`
	Width     int         `json:"width,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "height":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Height = int(in.Int())
			}
		case "uri":
			if in.IsNull() {
				in.Skip()
			} else {
				out.URI = string(in.String())
			}
		case "url_list":
			if in.IsNull() {
				in.Skip()
				out.URLList = nil
			} else {
				in.Delim('[')
				if out.URLList == nil {
					if !in.IsDelim(']') {
						out.URLList = make([]string, 0, 4)
					} else {
						out.URLList = []string{}
					}
				} else {
					out.URLList = (out.URLList)[:0]
				}
				for !in.IsDelim(']') {
					var v10 string
					if in.IsNull() {
						in.Skip()
					} else {
						v10 = string(in.String())
					}
					out.URLList = append(out.URLList, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "url_prefix":
			if m, ok := out.URLPrefix.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.URLPrefix.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.URLPrefix = in.Interface()
			}
		case "width":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Width = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1cedd36Encode5(out *jwriter.Writer, in struct {
	Height    int         `json:"height,omitempty"`
	URI       string      `json:"uri,omitempty"`
	URLList   []string    `json:"url_list,omitempty"`
	URLPrefix interface{} `json:"url_prefix,omitempty"`
	Width     int         `json:"width,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Height != 0 {
		const prefix string = ",\"height\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.Height))
	}
	if in.URI != "" {
		const prefix string = ",\"uri\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.URI))
	}
	if len(in.URLList) != 0 {
		const prefix string = ",\"url_list\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		{
			out.RawByte('[')
			for v11, v12 := range in.URLList {
				if v11 > 0 {
					out.RawByte(',')
				}
				out.String(string(v12))
			}
			out.RawByte(']')
		}
	}
	if in.URLPrefix != nil {
		const prefix string = ",\"url_prefix\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if m, ok := in.URLPrefix.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.URLPrefix.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.URLPrefix))
		}
	}
	if in.Width != 0 {
		const prefix string = ",\"width\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Width))
	}
	out.RawByte('}')
}
func easyjsonC1cedd36Decode1(in *jlexer.Lexer, out *struct {
	ID       string `json:"id,omitempty"`
	Title    string `json:"title,omitempty"`
	Play     string `json:"play,omitempty"`
	Cover    string `json:"cover,omitempty"`
	Author   string `json:"author,omitempty"`
	Original bool   `json:"original,omitempty"`
	Duration int    `json:"duration,omitempty"`
	Album    string `json:"album,omitempty"`
}) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "title":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Title = string(in.String())
			}
		case "play":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Play = string(in.String())
			}
		case "cover":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Cover = string(in.String())
			}
		case "author":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Author = string(in.String())
			}
		case "original":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Original = bool(in.Bool())
			}
		case "duration":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Duration = int(in.Int())
			}
		case "album":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Album = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonC1cedd36Encode1(out *jwriter.Writer, in struct {
	ID       string `json:"id,omitempty"`
	Title    string `json:"title,omitempty"`
	Play     string `json:"play,omitempty"`
	Cover    string `json:"cover,omitempty"`
	Author   string `json:"author,omitempty"`
	Original bool   `json:"original,omitempty"`
	Duration int    `json:"duration,omitempty"`
	Album    string `json:"album,omitempty"`
}) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != "" {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	if in.Title != "" {
		const prefix string = ",\"title\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Title))
	}
	if in.Play != "" {
		const prefix string = ",\"play\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Play))
	}
	if in.Cover != "" {
		const prefix string = ",\"cover\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Cover))
	}
	if in.Author != "" {
		const prefix string = ",\"author\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Author))
	}
	if in.Original {
		const prefix string = ",\"original\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Bool(bool(in.Original))
	}
	if in.Duration != 0 {
		const prefix string = ",\"duration\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.Duration))
	}
	if in.Album != "" {
		const prefix string = ",\"album\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Album))
	}
	out.RawByte('}')
}
